language: cpp

matrix:
  include:
    # Lua 5.3
    - env: LUA_VERSION=5.3.5 COMPILER=g++-4.9
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']

    - env: LUA_VERSION=5.3.5 COMPILER=g++-5
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

    - env: LUA_VERSION=5.3.5 COMPILER=g++-6
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

    - env: LUA_VERSION=5.3.5 COMPILER=clang++-3.9
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
          packages: ['clang-3.9']

    # - env: LUA_VERSION=5.3.5 COMPILER=clang++-4.0
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
    #       packages: ['clang-4.0']

    - env: LUA_VERSION=5.3.5 COMPILER=clang++-3.8
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']

    - env: LUA_VERSION=5.3.5 COMPILER=clang++-3.7
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']

    # Lua 5.2
    - env: LUA_VERSION=5.2.4 COMPILER=g++-4.9
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']

    - env: LUA_VERSION=5.2.4 COMPILER=g++-5
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

    - env: LUA_VERSION=5.2.4 COMPILER=g++-6
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

    - env: LUA_VERSION=5.2.4 COMPILER=clang++-3.9
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
          packages: ['clang-3.9']

    # - env: LUA_VERSION=5.2.4 COMPILER=clang++-4.0
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
    #       packages: ['clang-4.0']


    - env: LUA_VERSION=5.2.4 COMPILER=clang++-3.8
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']

    - env: LUA_VERSION=5.2.4 COMPILER=clang++-3.7
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']

    # Lua 5.1
    - env: LUA_VERSION=5.1.5 COMPILER=g++-4.9
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']

    - env: LUA_VERSION=5.1.5 COMPILER=g++-5
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

    - env: LUA_VERSION=5.1.5 COMPILER=g++-6
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

    - env: LUA_VERSION=5.1.5 COMPILER=clang++-3.9
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
          packages: ['clang-3.9']

    # - env: LUA_VERSION=5.1.5 COMPILER=clang++-4.0
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
    #       packages: ['clang-4.0']

    - env: LUA_VERSION=5.1.5 COMPILER=clang++-3.8
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']

    - env: LUA_VERSION=5.1.5 COMPILER=clang++-3.7
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']

    # LuaJIT 2.0.4
    - env: LUAJIT_VERSION=2.0.4 COMPILER=g++-4.9
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']

    - env: LUAJIT_VERSION=2.0.4 COMPILER=g++-5
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']

    - env: LUAJIT_VERSION=2.0.4 COMPILER=g++-6
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-6']

    - env: LUAJIT_VERSION=2.0.4 COMPILER=clang++-3.9
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
          packages: ['clang-3.9']

    # - env: LUAJIT_VERSION=2.0.4 COMPILER=clang++-4.0
    #   compiler: clang
    #   addons:
    #     apt:
    #       sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise']
    #       packages: ['clang-4.0']

    - env: LUAJIT_VERSION=2.0.4 COMPILER=clang++-3.8
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.8']
          packages: ['clang-3.8']

    - env: LUAJIT_VERSION=2.0.4 COMPILER=clang++-3.7
      compiler: clang
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.7']
          packages: ['clang-3.7']

cache:
  directories:
    - deps/download-cache

before_install:
  - if [[ -n "$COMPILER" ]]; then export CXX="$COMPILER"; fi

install:
  - source deps/install-lua.sh
  - test -e "$LUA_SRCDIR/lib$LUA_LIBNAME.a"
  - test -e "$LUA_SRCDIR/lua.h"

script:
  - make LUA_LIBDIR="$LUA_SRCDIR" LUA_INCDIR="$LUA_SRCDIR" LUA_LIBNAME="$LUA_LIBNAME" all

addons:
  apt:
    packages:
      - make
      - wget
